export const tableData = [
  {
    id: 1,
    name: "John Doe",
    age: 28,
    email: "john@gmail.com",
    phone: "123-456-7890",
    status: "active",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 34,
    email: "smith@gmail.com",
    phone: "987-654-3210",
    status: (
      <span className="inline-block px-2 py-1 text-xs font-medium text-green-700 bg-green-100 rounded-full">
        Inactive
      </span>
    ),
  },
  {
    id: 3,
    name: "Alice Johnson",
    age: 45,
    email: "alice@gmail.com",
    phone: "555-555-5555",
    status: "active",
  },
  {
    id: 4,
    name: "Bob Brown",
    age: 29,
    email: "bob@gmail.com",
    phone: "444-444-4444",
    status: "inactive",
  },
  {
    id: 5,
    name: "Charlie White",
    age: 32,
    email: "charlie@gmail.com",
    phone: "333-333-3333",
    status: "active",
  },
  {
    id: 6,
    name: "Diana Green",
    age: 41,
    email: "diana@gmail.com",
    phone: "222-222-2222",
    status: "inactive",
  },
  {
    id: 7,
    name: "Ethan Black",
    age: 27,
    email: "ethan@gmail.com",
    phone: "111-111-1111",
    status: "active",
  },
  {
    id: 8,
    name: "Fiona Blue",
    age: 35,
    email: "fiona@gmail.com",
    phone: "888-888-8888",
    status: "inactive",
  },
  {
    id: 9,
    name: "George Red",
    age: 38,
    email: "george@gmail.com",
    phone: "777-777-7777",
    status: "active",
  },
  {
    id: 10,
    name: "Hannah Violet",
    age: 30,
    email: "hannah@gmail.com",
    phone: "666-666-6666",
    status: "inactive",
  },
  {
    id: 11,
    name: "Isaac Orange",
    age: 39,
    email: "isaac@gmail.com",
    phone: "123-789-4560",
    status: "active",
  },
  {
    id: 12,
    name: "Julia Yellow",
    age: 36,
    email: "julia@gmail.com",
    phone: "234-567-8901",
    status: "inactive",
  },
  {
    id: 13,
    name: "Kevin Gray",
    age: 42,
    email: "kevin@gmail.com",
    phone: "345-678-9012",
    status: "active",
  },
  {
    id: 14,
    name: "Luna Pink",
    age: 33,
    email: "luna@gmail.com",
    phone: "456-789-0123",
    status: "inactive",
  },
  {
    id: 15,
    name: "Mason Purple",
    age: 26,
    email: "mason@gmail.com",
    phone: "567-890-1234",
    status: "active",
  },
  {
    id: 16,
    name: "Nora Indigo",
    age: 37,
    email: "nora@gmail.com",
    phone: "678-901-2345",
    status: "inactive",
  },
  {
    id: 17,
    name: "Oscar Gold",
    age: 43,
    email: "oscar@gmail.com",
    phone: "789-012-3456",
    status: "active",
  },
  {
    id: 18,
    name: "Paula Silver",
    age: 40,
    email: "paula@gmail.com",
    phone: "890-123-4567",
    status: "inactive",
  },
  {
    id: 19,
    name: "Quinn Bronze",
    age: 31,
    email: "quinn@gmail.com",
    phone: "901-234-5678",
    status: "active",
  },
  {
    id: 20,
    name: "Rita Copper",
    age: 44,
    email: "rita@gmail.com",
    phone: "012-345-6789",
    status: "inactive",
  },
  {
    id: 21,
    name: "Sam Iron",
    age: 28,
    email: "sam@gmail.com",
    phone: "987-123-4567",
    status: "active",
  },
  {
    id: 22,
    name: "Tina Steel",
    age: 34,
    email: "tina@gmail.com",
    phone: "876-234-5678",
    status: "inactive",
  },
  {
    id: 23,
    name: "Umar Lead",
    age: 35,
    email: "umar@gmail.com",
    phone: "765-345-6789",
    status: "active",
  },
  {
    id: 24,
    name: "Vera Zinc",
    age: 29,
    email: "vera@gmail.com",
    phone: "654-456-7890",
    status: "inactive",
  },
  {
    id: 25,
    name: "Will Mercury",
    age: 36,
    email: "will@gmail.com",
    phone: "543-567-8901",
    status: "active",
  },
  {
    id: 26,
    name: "Xena Titan",
    age: 32,
    email: "xena@gmail.com",
    phone: "432-678-9012",
    status: "inactive",
  },
  {
    id: 27,
    name: "Yara Nickel",
    age: 38,
    email: "yara@gmail.com",
    phone: "321-789-0123",
    status: "active",
  },
  {
    id: 28,
    name: "Zack Platinum",
    age: 31,
    email: "zack@gmail.com",
    phone: "210-890-1234",
    status: "inactive",
  },
  {
    id: 29,
    name: "Amber Clay",
    age: 40,
    email: "amber@gmail.com",
    phone: "109-901-2345",
    status: "active",
  },
  {
    id: 30,
    name: "Blake Quartz",
    age: 39,
    email: "blake@gmail.com",
    phone: "098-012-3456",
    status: "inactive",
  },
  {
    id: 31,
    name: "Cara Jade",
    age: 27,
    email: "cara@gmail.com",
    phone: "321-432-6543",
    status: "active",
  },
  {
    id: 32,
    name: "Derek Onyx",
    age: 42,
    email: "derek@gmail.com",
    phone: "432-543-7654",
    status: "inactive",
  },
  {
    id: 33,
    name: "Eliza Ruby",
    age: 33,
    email: "eliza@gmail.com",
    phone: "543-654-8765",
    status: "active",
  },
  {
    id: 34,
    name: "Finn Sapphire",
    age: 44,
    email: "finn@gmail.com",
    phone: "654-765-9876",
    status: "inactive",
  },
  {
    id: 35,
    name: "Gina Topaz",
    age: 26,
    email: "gina@gmail.com",
    phone: "765-876-0987",
    status: "active",
  },
  {
    id: 36,
    name: "Henry Amber",
    age: 41,
    email: "henry@gmail.com",
    phone: "876-987-1098",
    status: "inactive",
  },
  {
    id: 37,
    name: "Isla Emerald",
    age: 30,
    email: "isla@gmail.com",
    phone: "987-098-2109",
    status: "active",
  },
  {
    id: 38,
    name: "Jack Garnet",
    age: 29,
    email: "jack@gmail.com",
    phone: "098-109-3210",
    status: "inactive",
  },
  {
    id: 39,
    name: "Kara Opal",
    age: 43,
    email: "kara@gmail.com",
    phone: "219-210-4321",
    status: "active",
  },
  {
    id: 40,
    name: "Liam Pearl",
    age: 36,
    email: "liam@gmail.com",
    phone: "320-321-5432",
    status: "inactive",
  },
  {
    id: 41,
    name: "Mila Jade",
    age: 34,
    email: "mila@gmail.com",
    phone: "431-432-6543",
    status: "active",
  },
  {
    id: 42,
    name: "Noah Quartz",
    age: 38,
    email: "noah@gmail.com",
    phone: "542-543-7654",
    status: "inactive",
  },
  {
    id: 43,
    name: "Olivia Ruby",
    age: 25,
    email: "olivia@gmail.com",
    phone: "653-654-8765",
    status: "active",
  },
  {
    id: 44,
    name: "Paul Topaz",
    age: 39,
    email: "paul@gmail.com",
    phone: "764-765-9876",
    status: "inactive",
  },
  {
    id: 45,
    name: "Quincy Onyx",
    age: 31,
    email: "quincy@gmail.com",
    phone: "875-876-0987",
    status: "active",
  },
  {
    id: 46,
    name: "Rachel Sapphire",
    age: 37,
    email: "rachel@gmail.com",
    phone: "986-987-1098",
    status: "inactive",
  },
  {
    id: 47,
    name: "Steve Emerald",
    age: 35,
    email: "steve@gmail.com",
    phone: "097-098-2109",
    status: "active",
  },
  {
    id: 48,
    name: "Tara Garnet",
    age: 33,
    email: "tara@gmail.com",
    phone: "208-109-3210",
    status: "inactive",
  },
  {
    id: 49,
    name: "Usha Pearl",
    age: 30,
    email: "usha@gmail.com",
    phone: "319-210-4321",
    status: "active",
  },
  {
    id: 50,
    name: "Victor Opal",
    age: 40,
    email: "victor@gmail.com",
    phone: "420-321-5432",
    status: "inactive",
  },
];