import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AdminThemeProvider from "@/components/providers/AdminThemeProvider";
import PermissionGuard from "@/components/providers/PermissionGuard";
import AdminLayout from "@/components/layouts/AdminLayout";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminRootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <AdminThemeProvider>
            <PermissionGuard>
              <AdminLayout>
                {children}
              </AdminLayout>
            </PermissionGuard>
          </AdminThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
